# Generated by Django 3.2.4 on 2024-07-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='descuento',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.PositiveIntegerField(),
        ),
    ]
